### ISSUE TITLE
Comment on draft regarding overlap with ACCNAME and ROLES

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/personalization-semantics#135]
I think there is quite a bit of overlap with the accessible name and role of elements. Devs may ask, why do we have to repeat the same thing in the accname AND the personalization attributes.

we may want to introduce a generic value in each category.  we might want to introduce a section under each of the following that says "if the Accessible name and/orrole sufficiently describes the personalization characteristics, then the AT will do the heavy lifting to map it over instead of the developer.

- action
- Destination
- purpose
- distraction

The AT would use the accname or role and map it over accordingly.

### Example 1
```<aside>...</aside>```
content could get a generic "distraction" semantic without the data-distraction
### Example 2
```<a href...>[any of the tokens in the destination]</a> ```
would inherit that data-value by the AT

Same with a button... 
this way if devs are using overlapping accessible names or roles they don't have to add work and code. The AT would do the work.

**Comment by johnfoliot** [comment]
Hi 
David,

Thanks for your comments. There is a crucial difference between what we are seeking to do here, and the use-cases you have brought forward.

1. Suggesting that an `<aside>` is a distraction is incorrect: it may also contain 'critical' content to the end user, but in the context of an aside.  `<aside>` is a sectioning container, but does not apply any 'value-judgement' to the content (nor was it intended to do so)

We had envisioned distractions as content not related to the principle 'raison d'etre' of the page - and an aside might be included as part of that principle content. (A distraction might also be a flashing advertisement or other looped content). In the beginning, we envision this being added to content *after the fact* (we've previously discussed proxy servers, etc.), or used in other non-traditional use-cases (think IoT interfaces...). The determination of "distracting" will require a judgement call at some level: human at first but with a look to the future (and AI). However, we are still looking at machine-to-machine communication here: our attributes and values are intended for machines. The Accessible Name does not meet that criteria.

2. Accessible names are localized to the end user: the "accessible name" for an image in Quebec would be the @alt text en francais (alt="voiture"). Our goal is to have fixed token terms whenever possible as our attributes are not intended for humans, but rather machines.

> Example 2
> `<a href...>[any of the tokens in the destination]</a>` would inherit that data-value by the AT
>
> Same with a button...

Again, how would an AT tool *know* what a button label of "다음 단계로 이동" means? The Korean human "hearing" that from a screen reader would understand that the screen reader was saying "da-eum dangyelo idong" but the machine *still* doesn't know that the button is "saying" or means (**Take it to the next level** (i.e. Submit)) . Whether an action or a destination (Get or Post) our goal is to disambiguate it for machines, which is why we have fixed taxonomies.

HTH
