### ISSUE TITLE
Unclear support for color contrast and CSS with symbols

### ISSUE THREAD

**Issue by xi** [w3c/personalization-semantics#42]
The section on `aui-symbol` mentions the following example:

```html
<img aui-symbol="http://wordnet-rdf.princeton.edu/wn31/girl-n" href="mygirlsy.bmp" >
```

I imagine that a conforming user agent would render the appropriate symbol instead of the referenced image. But how can color contrast be guaranteed in this case?

We should also take into account that many pages today use icon fonts or inline SVG for symbols:

```html
<i aui-symbol="http://wordnet-rdf.princeton.edu/wn31/girl-n" class="fa fa-female"></i>
```

The benefit of this is that it is possible to style these with CSS, again allowing authors to control color contrast. How would `aui-symbol` work in these cases?

**Comment by johnfoliot** [comment]
Thank you for your enquiry.

As envisioned, data-symbol (formerly aui-symbol) is an attribute that is using a common taxonomy entry to reference the appropriate symbol from one of many different commercial and open-source symbol sets.  It is important to understand that the goal is to not just replace text with a symbol, but rather an "approved", pre-defined symbol taken from one of these sets. The symbols are the language, and different users learn different symbol sets to use to communicate. In fact, the taxonomical reference numbers we are using are taken from the Open Source Bliss symbol set (https://www.blissymbolics.org), although it is anticipated that other symbol sets will map back to that list.

Many of the symbol sets are monochromatic (black on white), whereas others may feature color. It is important to understand however that for users dependent on symbols, and choosing a specific set, they issue of color contrast will have already been addressed and resolved for those users - if a color blind user cannot function with "symbol set A" it will impact them on all content using those symbols, beyond just web-pages. As such, that user may have already chose to use a different "Set B" (as it were). It is expected (and in fact advised against) that content author will not be furnishing custom symbols to the user - provide the reference number, and let the user and user-settings handle which set the user has chosen. 

To the final question: because these symbols are already quite controlled in both color and physical appearance, there is no expectation that they can be further styled by the content author.

Closing this issue.

**Comment by johnfoliot** [comment]
Closing this issue.
