### ISSUE TITLE
Remove duplicate items in value tables

### ISSUE THREAD

**Issue by joanmarie** [w3c/personalization-semantics#65]
N.B. Edited because this issue was subsequently split into two as described in comments.

The actions table of values has duplicate (and in some cases triplicate) values. For instance `brightness` appears in the following rows (where the header row is row 1):
* row 43: "brightness: change or show the settings for the brightness."
* row 70: "brightness: adjust the screen or application brightness. Often used with increase or decrease but is sometimes used alone as a menu name or item."
* row 76: "adjust the screen or application brightness. Often used with increase or decrease but is sometimes used alone as a menu name or item. EDITOR'S NOTE: At risk pending implemetions (sic)."

Other duplicates in actions:
* `channel` (appears three times)
* `connect` (appears two times)
* `loop` (appears two times)
* `mediaPosition` (appears two times)
* `temperature` (appears three times)
* `volume` (appears three times)

Duplicate in destination:
* `related` (appears two times)

Extra row in field:
* Beneath the `bdayDay` row, there is a row with the same description ("day of birthday") but no name value.

**Comment by clapierre** [comment]
Thanks Joanmarie, I was aware of the sort order which is something that we were going to get to, as these were added in somewhat of a haphazard order due to common functionality themes.  But I agree sort order is good.  Will also look into the duplicates.  Would you be able to file these as two separate issues please in our GitHub repo issue tracker<https://github.com/w3c/personalization-semantics/issues>

Thanks
EOM

Charles LaPierre
Technical Lead, DIAGRAM and Born Accessible
E-mail: charlesl@benetech.org<mailto:charlesl@benetech.org>
Twitter: @CLaPierreA11Y
Skype: charles_lapierre
Phone: 650-600-3301



On Apr 10, 2018, at 6:26 AM, joanmarie <notifications@github.com<mailto:notifications@github.com>> wrote:

Duplicate items

The actions table of values has duplicate (and in some cases triplicate) values. For instance brightness appears in the following rows (where the header row is row 1):

  *   row 43: "brightness: change or show the settings for the brightness."
  *   row 70: "brightness: adjust the screen or application brightness. Often used with increase or decrease but is sometimes used alone as a menu name or item."
  *   row 76: "adjust the screen or application brightness. Often used with increase or decrease but is sometimes used alone as a menu name or item. EDITOR'S NOTE: At risk pending implemetions (sic)."

Other duplicates:

  *   channel (appears three times)
  *   connect (appears two times)
  *   loop (appears two times)
  *   mediaPosition (appears two times)
  *   temperature (appears three times)
  *   volume (appears three times)

Lack of sort order / grouping of values

The actions table of values does not appear to be grouped in any logical order. Two candidate orders spring to my mind:

  *   Alphabetical
  *   Functionality (email, purchases, media controls)

Other orders might make more sense. But given the size of the list (64 items when duplicates have been removed), I think some arrangement will make the list easier to process.

**Comment by joanmarie** [comment]
> Would you be able to file these as two separate issues please in our GitHub repo issue tracker

Done. Issue #67

**Comment by joanmarie** [comment]
Since I made a new issue for sorting, I editing the opening report and summary to make this issue just about duplicate items, and added a duplicate destination item.

**Comment by lseeman** [comment]
Thank you so much for your comment. We think the new draft has addressed it. We reduced the values or renamed where appropriate to remove duplicate names/values. See https://www.w3.org/TR/personalization-semantics-content-1.0/

**Comment by clapierre** [comment]
Here is a link to a sortable table to show the latest values has no duplicates.
https://raw.githack.com/w3c/personalization-semantics/rewrite-prototype/content/index.html#values
